# Generated by Django 3.2.5 on 2021-08-09 16:39

import app_roboq.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadIDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_username', models.CharField(max_length=255, unique=True)),
                ('doc_xml', models.FileField(upload_to=app_roboq.models.UploadIDS.get_upload_xml_path)),
            ],
        ),
    ]
